### ISSUE TITLE
Scroll Ring and Little Finger both working same setup

### ISSUE THREAD

**Issue by rug4ever** [fredemmott/hand-tracked-cockpit-clicking#23]
Hello i have a quest 2 and want to take the Baro knobster with hand tracking scrolling.
decrease its working good one onch per one step in baro 
but if i want take the little finger for increase not working 
the make same decrease the baro not increse 
its wronk on my side ? pls give me a reg command to change the incrwase on the little finger 

many thx

**Comment by fredemmott** [comment]
Sorry, this is provided by Oculus, and can only be improved by firmware/driver updates from them.
