### ISSUE TITLE
Left hand vs right hand differences in MSFS

### ISSUE THREAD

**Issue by wheeliemonster** [fredemmott/hand-tracked-cockpit-clicking#26]
Using ultraleap tracking with clicks mapped through HTCC, clicks and pointing work very well.
I have assigned joystick buttons to mouse scroll or even to other buttons (with mappings for cockpit interaction - increase/decrease in MSFS) to allow the operation of the rotaries.
The left hand works perfectly, however as soon as I rotate a dial using the right hand to point, the tracking ceases until I gesture with the left hand, then the right again (could this possibly linked to "perma-squeeze" issue: https://github.com/fredemmott/hand-tracked-cockpit-clicking/issues/24#issue-1522696352 ?)

**Comment by fredemmott** [comment]
I can't reproduce this with a build for fix for #24 

Does the  msi at the bottom of https://github.com/fredemmott/hand-tracked-cockpit-clicking/actions/runs/3862788049 fix this for you?

**Comment by fredemmott** [comment]
> however as soon as I rotate a dial using the right hand to point, the tracking ceases until I gesture with the left hand

Tracking will cease when you scroll until a 'controller' is activated again - this is just what MSFS does for scroll wheels :(

The behavior should no longer vary by hand though - any controller action (e.g. clicking at nothing) with either hand should re-activate it

**Comment by wheeliemonster** [comment]
> > however as soon as I rotate a dial using the right hand to point, the tracking ceases until I gesture with the left hand
> 
> Tracking will cease when you scroll until a 'controller' is activated again - this is just what MSFS does for scroll wheels :(
> 
> The behavior should no longer vary by hand though - any controller action (e.g. clicking at nothing) with either hand should re-activate it

Hey Fred. The newer build is worse actually, I now get the "bad" behaviour with both hands. I guess maybe the squeeze action being permanently pressed on the left hand was instantly reactivating the controller after the scroll action? Now I understand the way it works, I may be able to work around it by adding a "click" at the end of my scroll action. Obviously it would be better if I didn't have to do this (for other people of course!)

PS. I still needed to re-install Ultraleap AFTER updating to the new build - I ran your ListLayers script and they were swapped again :(

**Comment by fredemmott** [comment]
> Obviously it would be better if I didn't have to do this (for other people of course!

Sorry; at least it's consistent, but this appears to be intentional on MSFS's part. You can switch to using controller actions for the scroll to avoid this issue, but IMO those are just plain unusable (both with HTCC and with real controllers)

**Comment by wheeliemonster** [comment]
> > Obviously it would be better if I didn't have to do this (for other people of course!
> 
> Sorry; at least it's consistent, but this appears to be intentional on MSFS's part. You can switch to using controller actions for the scroll to avoid this issue, but IMO those are just plain unusable (both with HTCC and with real controllers)

No, I understand. Better to have consistent behaviour. What happens if you set both to "perma-squeeze"? Or does that cause other problems? I did find with the new build that I now have to click to wake the controllers after timeouts.

**Comment by fredemmott** [comment]
> What happens if you set both to "perma-squeeze"?

Both *were* set to perma-squeeze; the inconsistent behavior is built into MSFS :(

**Comment by wheeliemonster** [comment]
Sure, no worries. I know their controller implementation is bad!
All good. Thanks for the fix any way - I can work around it and HTCC's still an absolute game-changer for me so I really appreciate your work.

On 7 Jan 2023 22:05, Fred Emmott ***@***.***> wrote:

What happens if you set both to "perma-squeeze"?

Both were set to perma-squeeze; the inconsistent behavior is built into MSFS :(
