### ISSUE TITLE
Fix controller emulation compatibility with DCS's native OpenXR support

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/hand-tracked-cockpit-clicking#31]
While touch screen mode is recommended for DCS and controller emulation works fine in MSFS, both should work.

Controller emulation is currently only usable with DCS via OpenComposite.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/OpenXR-Tracing basically exists to figure out what's going on here :)

**Comment by nabbl** [comment]
Is this why I cant see the "hands" while in DCS cockpit?

Clicking stuff is working fine but when I cant see my hand in VR and only move the pointer it is kind of pointless

**Comment by fredemmott** [comment]
No; both sets of instructions include hiding your hand, as this project *intentionally* makes your hand not line up with the emulated controller, to increase stability/reduce shakiness.

The only way you're going to get usable hand tracking support with accurate rendering of hands is if Eagle Dynamics add it; given what's possible with DCS at the moment, you have to choose either 'usable for clicking' or 'accurate rendering of hands'. This project aims for 'usable for clicking'.
